# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         UTF8BOM
version:      0.01
version_from: lib/UTF8BOM.pm
installdirs:  site
requires:
    File::Spec:                    0
    IO::Dir:                       0
    IO::File:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
